Shellcheck passes. Skip sleep for low delays

diff --git a/typer b/typer
--- a/typer
+++ b/typer
@@ -24,46 +24,60 @@ EOF
     # return nicely on interrupt
     trap 'printf "\n"; return 2' SIGINT
     # get options
-    local rate=30 mode=0
-    while getopts ":hc:rs" opt; do
+    local rate=30 mode="random"
+    local opt OPTIND OPTARG
+    while getopts ":hc:qrs" opt; do
         case "$opt" in
             c) # rate in characters per second 0-999
                 rate="$OPTARG"
                 if [[ "$rate" -ge 1000 ]] || [[ "$rate" -le 0 ]]; then
-                    printf "Rate must be between 1 and 999.\n" >&2
+                    printf "Rate must be between 1 and 999.\\n" >&2
                     return 2
                 fi
                 ;;
             r) # random mode
-                mode=0
+                mode="random"
                 ;;
             s) # smooth mode
-                mode=1
+                mode="smooth"
                 ;;
-
+            q) # quick mode
+                mode="quick"
+                ;;
             h) # help?
-                printf "%s\n" "$use"
+                printf "%s\\n" "$use"
                 return 1
                 ;;
             \?) # invalid
-                printf  "Invalid option: -%s\n\n%s\n" "$OPTARG" "$use" >&2
+                printf  "Invalid option: -%s\\n\\n%s\\n" "$OPTARG" "$use" >&2
                 return 1
                 ;;
         esac
     done
+    # speed things up
+    if (( rate < 5 )); then
+        rate=0
+    fi
+
     # read one character at a time from standard input
-    local wait step
+    local delay=0
     while IFS= read -r -N 1 c; do
-        # calculate wait in thousanths of a second
-        if [ "$mode" -eq 1 ]; then
-            # smoothly
-            wait=$(printf "0.%03d" $(( 1000 / rate )) )
-        else
-            # randomly
-            wait=$(printf "0.%03d" $(( RANDOM % ( 2000 / rate ) )) )
-        fi
+        # calculate delay in thousanths of a second
+        case "$mode" in
+            smooth)
+                delay=$(printf "0.%03d" $(( 1000 / rate )) )
+                ;;
+            random)
+                delay=$(printf "0.%03d" $(( RANDOM % ( 2000 / rate ) )) )
+                ;;
+            quick)
+                delay=0
+                ;;
+        esac
         # delay that long
-        sleep "$wait"
+        if [ "$delay" != "0.000" ]; then
+            sleep "$delay"
+        fi
         # write the character
         printf "%s" "$c"
     done
